### PR TITLE
fix bug that breaks toArray() and toTransform()

### LINKED ISSUE #32: AbstractObjectTransformer break when transforming toArray() and toObject()
Instead of calling `$resorce->transform()` it should be calling `$this->transform()`

### PR DESCRIPTION
**Pull request by iampersistent**
Fixes #32

### CODE REVIEW

File: src/Transformer/AbstractObjectTransformer.php [hunk 1]
```diff
@@ -9,13 +9,13 @@
...
 
-    public function toObject(ResourceInterface $resource)
+    public function toArray(ResourceInterface $resource)
     {
-        return $resource->untransform($this);
+        return $this->transform($resource);
     }
 
-    public function toArray(ResourceInterface $resource)
+    public function toObject(ResourceInterface $resource)
```
Comment (ruskiyos) [inline src/Transformer/AbstractObjectTransformer.php]: what's the purpose of the `toObject` getter?
it seems misleads to "untransform" (even though objects do come it, transformers deal will arrayable data...

Comment (alexcoffee) [reply src/Transformer/AbstractObjectTransformer.php]: I think he is untransforming to Object (like serialize/unserialize)

Comment (ruskiyos) [reply src/Transformer/AbstractObjectTransformer.php]: ohh. because it's specifically on the `AbstractObjectTransformer`. makes sense

File: tests/unit/Transformer/Bug32Cest.php [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+declare(strict_types=1);
+
+namespace Test\Unit\Transformer;
+
+use Diaclone\Resource\ObjectItem;
+use Test\Unit\Support\Entities\Password;
+use Test\Unit\Support\Transformers\PayloadToPasswordTransformer;
+use UnitTester;
+
+class Bug32Cest
```
Comment (alexcoffee) [inline tests/unit/Transformer/Bug32Cest.php]: why is it called Bug32Cest?

Comment (iampersistent) [reply tests/unit/Transformer/Bug32Cest.php]: I put in a issue ticket #32 so I just made the test based on the issue. It wasn't a new feature, so I didn't really know what to call it. I'll change it if you have a suggestion.

Comment (iampersistent) [reply tests/unit/Transformer/Bug32Cest.php]: @alexcoffee do you need me to change this?

Comment (alexcoffee) [reply tests/unit/Transformer/Bug32Cest.php]: lol no it just made me curious
